### PR TITLE
modify udpSource to stream the sender's address with the message

### PR DESCRIPTION
**Pull request by mihaigiurgeanu**
This pull request implements the proposal in the issue #3. It also adds a new `Int` parameter to `udpSource` and `udpSourcePlain` setting the maximum size of datagram. I think, being about datagrams, the protocol designer should know the maximum size of the datagram and so, it will be faster to make a single call to `recvFrom` and not to test if there is some more data to come.

### CODE REVIEW

**Comment by kqr** [comment]
Neat! I want to merge this but I have three requests first. It'd be great if you could look over them.

- I'd like the version number in the cabal file to be bumped to indicate that backwards-incompatible API changes have happened. 
- I'd like the examples in the readme to be updated to compile with the new API.
- You should probably add your name to the copyright statements in the cabal file and LICENSE file.

Thank you for your interest in the library. I'm a bit curious also to see what you're making with it. :)

**Comment by mihaigiurgeanu** [comment]
Oh, great! Thanks. I will do the changes. I am using it to implement P2P fast communication to be used in a blockchain project (https://trusto.io/homepage/)

**Comment by mihaigiurgeanu** [comment]
I just updated the documentation, bumped version number to 0.2.0.0 and added my name to the copyright in the cabal and license file.

**Comment by kqr** [comment]
That's great, thank you. I'll have a look at your project page as well. Looks cool!

**Comment by mihaigiurgeanu** [comment]
Thanks. Just to let you know, I decided to go with streaming library instead of conduit, so I ported udp-conduit package to [upd-streaming](https://hackage.haskell.org/package/udp-streaming)

**Comment by kqr** [comment]
Ah, neat. I didn't even know streaming existed, but it looks promising performance-wise, at least! Probably a better fit for fire-and-forget style UDP communication. :)

**Pull request merged**
